import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export interface LineItem {
  id: string;
  product: string;
  qty: number;
  unitPrice: number;
}

interface OrderExport {
  id: string;
  customer: string;
  date: string;
  items: number;
  total: number;
  status: string;
}

interface InvoiceExport {
  id: string;
  customer: string;
  date: string;
  dueDate: string;
  amount: number;
  status: string;
}

interface CompanyInfo {
  companyName: string;
  address: string;
  city: string;
  country: string;
  email: string;
  phone: string;
  currency: string;
}

const SETTINGS_KEY = "biozentra-settings";

function loadCompanyInfo(): CompanyInfo {
  try {
    const stored = localStorage.getItem(SETTINGS_KEY);
    if (stored) {
      const s = JSON.parse(stored);
      return {
        companyName: s.companyName || "BIOZENTRA Healthcare",
        address: s.address || "",
        city: s.city || "",
        country: s.country || "",
        email: s.email || "",
        phone: s.phone || "",
        currency: s.currency || "PKR",
      };
    }
  } catch { /* ignore */ }
  return { companyName: "BIOZENTRA Healthcare", address: "", city: "", country: "", email: "", phone: "", currency: "PKR" };
}

function addPageFooters(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160);
    doc.text(
      `Page ${i} of ${pageCount}  •  Generated by Biozentra Healthcare Dashboard`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }
}

function drawHeader(doc: jsPDF, company: CompanyInfo, subtitle: string) {
  doc.setFillColor(22, 101, 52);
  doc.rect(0, 0, doc.internal.pageSize.width, 42, "F");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text(company.companyName || "BIOZENTRA Healthcare", 14, 17);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(subtitle, 14, 30);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-PK")}`, 135, 30);
}

export const exportOrdersToPDF = (orders: OrderExport[]) => {
  const company = loadCompanyInfo();
  const doc = new jsPDF();
  const curr = company.currency || "PKR";
  drawHeader(doc, company, "Orders Report");

  autoTable(doc, {
    startY: 52,
    head: [["Order ID", "Customer", "Date", "Items", `Total (${curr})`, "Status"]],
    body: orders.map((o) => [o.id, o.customer, o.date, o.items.toString(), o.total.toLocaleString(), o.status]),
    headStyles: { fillColor: [22, 101, 52], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [240, 253, 244] },
    styles: { fontSize: 9, cellPadding: 4 },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 5) {
        const s = data.cell.raw as string;
        if (s === "Delivered") data.cell.styles.textColor = [22, 101, 52];
        else if (s === "Pending") data.cell.styles.textColor = [161, 98, 7];
        else if (s === "Cancelled") data.cell.styles.textColor = [185, 28, 28];
      }
    },
  });
  addPageFooters(doc);
  doc.save(`biozentra-orders-${new Date().toISOString().split("T")[0]}.pdf`);
};

export const exportInvoicesToPDF = (invoices: InvoiceExport[]) => {
  const company = loadCompanyInfo();
  const doc = new jsPDF();
  const curr = company.currency || "PKR";
  drawHeader(doc, company, "Invoices Report");

  const totalAmt = invoices.reduce((s, i) => s + i.amount, 0);
  const paidAmt = invoices.filter(i => i.status === "Paid").reduce((s, i) => s + i.amount, 0);
  const pendingAmt = invoices.filter(i => i.status === "Pending").reduce((s, i) => s + i.amount, 0);

  doc.setFontSize(9); doc.setTextColor(30);
  doc.text(`Total: ${curr} ${totalAmt.toLocaleString()}`, 14, 52);
  doc.text(`Paid: ${curr} ${paidAmt.toLocaleString()}`, 80, 52);
  doc.text(`Pending: ${curr} ${pendingAmt.toLocaleString()}`, 146, 52);

  autoTable(doc, {
    startY: 60,
    head: [["Invoice ID", "Customer", "Date", "Due Date", `Amount (${curr})`, "Status"]],
    body: invoices.map((inv) => [inv.id, inv.customer, inv.date, inv.dueDate, inv.amount.toLocaleString(), inv.status]),
    headStyles: { fillColor: [22, 101, 52], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [240, 253, 244] },
    styles: { fontSize: 9, cellPadding: 4 },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 5) {
        const s = data.cell.raw as string;
        if (s === "Paid") data.cell.styles.textColor = [22, 101, 52];
        else if (s === "Overdue") data.cell.styles.textColor = [185, 28, 28];
        else if (s === "Pending") data.cell.styles.textColor = [161, 98, 7];
      }
    },
  });
  addPageFooters(doc);
  doc.save(`biozentra-invoices-${new Date().toISOString().split("T")[0]}.pdf`);
};

export const exportSingleInvoicePDF = (invoice: InvoiceExport, lineItems?: LineItem[]) => {
  const company = loadCompanyInfo();
  const doc = new jsPDF();
  const curr = company.currency || "PKR";
  const W = doc.internal.pageSize.width;

  // ── Header bar ─────────────────────────────────────────────────────────────
  doc.setFillColor(22, 101, 52);
  doc.rect(0, 0, W, 46, "F");

  doc.setFontSize(22); doc.setTextColor(255, 255, 255); doc.setFont("helvetica", "bold");
  doc.text(company.companyName || "BIOZENTRA Healthcare", 14, 17);

  doc.setFontSize(9); doc.setFont("helvetica", "normal");
  const addrParts = [company.address, company.city, company.country].filter(Boolean);
  if (addrParts.length) doc.text(addrParts.join(", "), 14, 27);
  const contactParts = [company.email, company.phone].filter(Boolean);
  if (contactParts.length) doc.text(contactParts.join("  |  "), 14, 36);

  // Invoice label right side
  doc.setFontSize(18); doc.setFont("helvetica", "bold");
  doc.text("INVOICE", W - 14, 17, { align: "right" });
  doc.setFontSize(10); doc.setFont("helvetica", "normal");
  doc.text(invoice.id, W - 14, 27, { align: "right" });
  doc.setFontSize(9);
  doc.text(`Issue: ${invoice.date}`, W - 14, 36, { align: "right" });

  // ── Bill To + Invoice details ──────────────────────────────────────────────
  const y0 = 58;
  doc.setDrawColor(220); doc.setLineWidth(0.3);
  doc.line(14, 54, W - 14, 54);

  doc.setFontSize(8); doc.setTextColor(120);
  doc.text("BILL TO", 14, y0);
  doc.setFontSize(13); doc.setTextColor(20); doc.setFont("helvetica", "bold");
  doc.text(invoice.customer, 14, y0 + 8);
  doc.setFont("helvetica", "normal");

  // Right side details box
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(W - 80, y0 - 4, 66, 38, 2, 2, "F");
  doc.setFontSize(8); doc.setTextColor(100);
  const boxX = W - 76;
  doc.text("Invoice No:", boxX, y0 + 4);
  doc.text("Issue Date:", boxX, y0 + 13);
  doc.text("Due Date:", boxX, y0 + 22);
  doc.setTextColor(20); doc.setFont("helvetica", "bold"); doc.setFontSize(8);
  doc.text(invoice.id, boxX + 22, y0 + 4);
  doc.text(invoice.date, boxX + 22, y0 + 13);
  doc.text(invoice.dueDate, boxX + 22, y0 + 22);

  // Status badge
  const statusColors: Record<string, [number, number, number]> = {
    Paid: [22, 101, 52], Pending: [161, 98, 7], Overdue: [185, 28, 28],
  };
  const col = statusColors[invoice.status] || [80, 80, 80];
  doc.setFillColor(...col);
  doc.roundedRect(14, y0 + 14, 28, 8, 1.5, 1.5, "F");
  doc.setFontSize(7.5); doc.setTextColor(255); doc.setFont("helvetica", "bold");
  doc.text(invoice.status.toUpperCase(), 28, y0 + 19.5, { align: "center" });

  // ── Line items table ───────────────────────────────────────────────────────
  const tableStartY = y0 + 42;

  if (lineItems && lineItems.length > 0) {
    autoTable(doc, {
      startY: tableStartY,
      head: [["#", "Item / Product", "Qty", `Unit Price (${curr})`, `Total (${curr})`]],
      body: lineItems.map((item, i) => [
        (i + 1).toString(),
        item.product,
        item.qty.toString(),
        item.unitPrice.toLocaleString(),
        (item.qty * item.unitPrice).toLocaleString(),
      ]),
      headStyles: { fillColor: [22, 101, 52], textColor: 255, fontStyle: "bold", fontSize: 9 },
      alternateRowStyles: { fillColor: [240, 253, 244] },
      styles: { fontSize: 9, cellPadding: 3.5 },
      columnStyles: {
        0: { halign: "center", cellWidth: 12 },
        2: { halign: "center", cellWidth: 18 },
        3: { halign: "right", cellWidth: 36 },
        4: { halign: "right", cellWidth: 36 },
      },
    });
  }

  // ── Amount Due box ─────────────────────────────────────────────────────────
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const afterTable = (doc as any).lastAutoTable?.finalY ?? tableStartY + 20;
  const amtY = afterTable + 8;

  doc.setFillColor(22, 101, 52);
  doc.roundedRect(W - 80, amtY, 66, 22, 2, 2, "F");
  doc.setFontSize(8); doc.setTextColor(200, 255, 200); doc.setFont("helvetica", "normal");
  doc.text("AMOUNT DUE", W - 47, amtY + 8, { align: "center" });
  doc.setFontSize(14); doc.setTextColor(255); doc.setFont("helvetica", "bold");
  doc.text(`${curr} ${invoice.amount.toLocaleString()}`, W - 47, amtY + 17, { align: "center" });

  // ── Footer ─────────────────────────────────────────────────────────────────
  const pH = doc.internal.pageSize.height;
  doc.setDrawColor(22, 101, 52); doc.setLineWidth(0.5);
  doc.line(14, pH - 22, W - 14, pH - 22);
  doc.setFontSize(9); doc.setTextColor(100); doc.setFont("helvetica", "normal");
  doc.text("Thank you for your business!", 14, pH - 15);
  doc.text("Generated by Biozentra Healthcare Dashboard", 14, pH - 9);

  doc.save(`${invoice.id}.pdf`);
};
