import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface OrderExport {
  id: string;
  customer: string;
  date: string;
  items: number;
  total: number;
  status: string;
}

interface InvoiceExport {
  id: string;
  customer: string;
  date: string;
  dueDate: string;
  amount: number;
  status: string;
}

interface CompanyInfo {
  companyName: string;
  address: string;
  city: string;
  country: string;
  email: string;
  phone: string;
  currency: string;
}

const SETTINGS_KEY = "biozentra-settings";

function loadCompanyInfo(): CompanyInfo {
  try {
    const stored = localStorage.getItem(SETTINGS_KEY);
    if (stored) {
      const s = JSON.parse(stored);
      return {
        companyName: s.companyName || "BIOZENTRA Healthcare",
        address: s.address || "",
        city: s.city || "",
        country: s.country || "",
        email: s.email || "",
        phone: s.phone || "",
        currency: s.currency || "PKR",
      };
    }
  } catch {
    // ignore
  }
  return {
    companyName: "BIOZENTRA Healthcare",
    address: "",
    city: "",
    country: "",
    email: "",
    phone: "",
    currency: "PKR",
  };
}

function addPageFooters(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}  •  Generated by Biozentra Healthcare Dashboard`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }
}

export const exportOrdersToPDF = (orders: OrderExport[]) => {
  const company = loadCompanyInfo();
  const doc = new jsPDF();
  const curr = company.currency || "PKR";

  // Header bar
  doc.setFillColor(22, 101, 52); // dark green
  doc.rect(0, 0, doc.internal.pageSize.width, 40, "F");

  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text(company.companyName || "BIOZENTRA Healthcare", 14, 18);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Orders Report", 14, 30);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-PK")}`, 140, 30);

  // Table
  autoTable(doc, {
    startY: 50,
    head: [["Order ID", "Customer", "Date", "Items", `Total (${curr})`, "Status"]],
    body: orders.map((o) => [
      o.id,
      o.customer,
      o.date,
      o.items.toString(),
      o.total.toLocaleString(),
      o.status,
    ]),
    headStyles: { fillColor: [22, 101, 52], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [240, 253, 244] },
    styles: { fontSize: 9, cellPadding: 4 },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 5) {
        const s = data.cell.raw as string;
        if (s === "Delivered") data.cell.styles.textColor = [22, 101, 52];
        else if (s === "Pending") data.cell.styles.textColor = [161, 98, 7];
        else if (s === "Cancelled") data.cell.styles.textColor = [185, 28, 28];
      }
    },
  });

  addPageFooters(doc);
  doc.save(`biozentra-orders-${new Date().toISOString().split("T")[0]}.pdf`);
};

export const exportInvoicesToPDF = (invoices: InvoiceExport[]) => {
  const company = loadCompanyInfo();
  const doc = new jsPDF();
  const curr = company.currency || "PKR";

  // Header bar
  doc.setFillColor(22, 101, 52);
  doc.rect(0, 0, doc.internal.pageSize.width, 40, "F");

  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text(company.companyName || "BIOZENTRA Healthcare", 14, 18);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Invoices Report", 14, 30);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-PK")}`, 140, 30);

  // Summary stats
  const totalAmt = invoices.reduce((s, i) => s + i.amount, 0);
  const paidAmt = invoices.filter(i => i.status === "Paid").reduce((s, i) => s + i.amount, 0);
  const pendingAmt = invoices.filter(i => i.status === "Pending").reduce((s, i) => s + i.amount, 0);

  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  doc.text(`Total: ${curr} ${totalAmt.toLocaleString()}`, 14, 50);
  doc.text(`Paid: ${curr} ${paidAmt.toLocaleString()}`, 80, 50);
  doc.text(`Pending: ${curr} ${pendingAmt.toLocaleString()}`, 146, 50);

  autoTable(doc, {
    startY: 58,
    head: [["Invoice ID", "Customer", "Date", "Due Date", `Amount (${curr})`, "Status"]],
    body: invoices.map((inv) => [
      inv.id,
      inv.customer,
      inv.date,
      inv.dueDate,
      inv.amount.toLocaleString(),
      inv.status,
    ]),
    headStyles: { fillColor: [22, 101, 52], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [240, 253, 244] },
    styles: { fontSize: 9, cellPadding: 4 },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 5) {
        const s = data.cell.raw as string;
        if (s === "Paid") data.cell.styles.textColor = [22, 101, 52];
        else if (s === "Overdue") data.cell.styles.textColor = [185, 28, 28];
        else if (s === "Pending") data.cell.styles.textColor = [161, 98, 7];
      }
    },
  });

  addPageFooters(doc);
  doc.save(`biozentra-invoices-${new Date().toISOString().split("T")[0]}.pdf`);
};

export const exportSingleInvoicePDF = (invoice: InvoiceExport) => {
  const company = loadCompanyInfo();
  const doc = new jsPDF();
  const curr = company.currency || "PKR";

  // Top green header bar
  doc.setFillColor(22, 101, 52);
  doc.rect(0, 0, doc.internal.pageSize.width, 45, "F");

  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text(company.companyName || "BIOZENTRA Healthcare", 14, 18);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const addressParts = [company.address, company.city, company.country].filter(Boolean);
  if (addressParts.length > 0) doc.text(addressParts.join(", "), 14, 27);
  const contactParts = [company.email, company.phone].filter(Boolean);
  if (contactParts.length > 0) doc.text(contactParts.join("  |  "), 14, 35);

  // Invoice label (right side of header)
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 150, 20);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(invoice.id, 150, 30);
  doc.setFontSize(9);
  doc.text(`Date: ${invoice.date}`, 150, 38);

  // Divider
  doc.setDrawColor(22, 101, 52);
  doc.setLineWidth(0.5);
  doc.line(14, 55, 196, 55);

  // Bill To section
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("BILL TO:", 14, 65);
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.text(invoice.customer, 14, 73);
  doc.setFont("helvetica", "normal");

  // Invoice details box
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(120, 58, 76, 55, 3, 3, "F");
  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text("Invoice No:", 128, 68);
  doc.text("Issue Date:", 128, 78);
  doc.text("Due Date:", 128, 88);
  doc.setTextColor(20);
  doc.setFont("helvetica", "bold");
  doc.text(invoice.id, 162, 68);
  doc.text(invoice.date, 162, 78);
  doc.text(invoice.dueDate, 162, 88);

  // Amount Due
  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.setFont("helvetica", "normal");
  doc.text("AMOUNT DUE", 128, 100);
  doc.setFontSize(15);
  doc.setTextColor(22, 101, 52);
  doc.setFont("helvetica", "bold");
  doc.text(`${curr} ${invoice.amount.toLocaleString()}`, 128, 109);

  // Status badge
  const statusColors: Record<string, [number, number, number]> = {
    Paid: [22, 101, 52],
    Pending: [161, 98, 7],
    Overdue: [185, 28, 28],
  };
  const col = statusColors[invoice.status] || [80, 80, 80];
  doc.setFillColor(...col);
  doc.roundedRect(14, 83, 35, 10, 2, 2, "F");
  doc.setFontSize(9);
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.text(invoice.status.toUpperCase(), 31.5, 89.5, { align: "center" });

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(130);
  doc.setFont("helvetica", "normal");
  doc.line(14, doc.internal.pageSize.height - 22, 196, doc.internal.pageSize.height - 22);
  doc.text("Thank you for your business!", 14, doc.internal.pageSize.height - 16);
  doc.text("Generated by Biozentra Healthcare Dashboard", 14, doc.internal.pageSize.height - 10);

  doc.save(`${invoice.id}.pdf`);
};
